<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.jobtracker</groupId>
    <artifactId>alexandra-job-tracker</artifactId>
    <version>1.0.0</version>
  </parent>

  <artifactId>infrastructure-ai</artifactId>
  <name>Infrastructure AI</name>
  <description>Infrastructure layer responsible for AI-related functionalities.</description>

  <dependencies>
    <dependency>
      <groupId>com.jobtracker</groupId>
      <artifactId>domain</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.ai</groupId>
      <artifactId>spring-ai-starter-model-openai</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
  </dependencies>
</project>
