version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule: { interval: weekly, day: monday }
    open-pull-requests-limit: 10
    labels: [ dependencies, automated ]
    groups:
      maven-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/deploy/compose"
    schedule: { interval: weekly }
    labels: [ infrastructure, automated ]
    groups:
      infrastructure-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/deploy/aws"
    schedule: { interval: weekly }
    labels: [ infrastructure, automated ]
    groups:
      infrastructure-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker-compose
    directory: "/deploy/compose"
    schedule: { interval: weekly }
    labels: [ infrastructure, automated ]
    groups:
      infrastructure-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/deploy/aws/terraform/templates"
    schedule: { interval: weekly }
    labels: [ infrastructure, automated ]
    groups:
      infrastructure-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: weekly }
    labels: [ ci, automated ]
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
