info:
  name: mutation.deleteApplication
  type: graphql
  seq: 7

graphql:
  method: POST
  url: "{{baseUrl}}/graphql"
  headers:
    - name: Accept
      value: application/json
  body:
    query: |
      mutation($id: ID!) { 
        deleteApplication(id: $id)
      }
    variables: |-
      {
         "id": "{{randomId}}"
      }
  auth: inherit

runtime:
  variables:
    - name: randomId
      value: 4169083b-35d7-4dcd-8471-ccda0d8d4c6e

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
