info:
  name: mutation.updateApplicationStatus
  type: graphql
  seq: 5

graphql:
  method: POST
  url: "{{baseUrl}}/graphql"
  headers:
    - name: Accept
      value: application/json
  body:
    query: |
      mutation($id: ID!, $status: ApplicationStatus!, $notes: String) { 
        updateApplicationStatus(id: $id, status: $status, notes: $notes) {
          id, company, role, source, postingUrl, notes, status, dateApplied, lastUpdated
        }
      }
    variables: |-
      {
        "id": "{{randomId}}",
        "status": "{{randomStatus}}",
        "notes": "{{randomNotes}}"
      }
  auth: inherit

runtime:
  variables:
    - name: randomId
      value: 4169083b-35d7-4dcd-8471-ccda0d8d4c6e
    - name: randomStatus
      value: OFFER
    - name: randomNotes
      value: Status changed
  scripts:
    - type: before-request
      code: |-
        const states = [
          "SAVED", 
          "APPLIED", 
          "INTERVIEWING", 
          "OFFER", 
          "ACCEPTED", 
          "REJECTED", 
          "WITHDRAWN"
        ];

        const randomStatus = states[Math.floor(Math.random() * states.length)];
        bru.setVar("randomStatus", randomStatus);
        bru.setVar("randomNotes", "Status changed: " + randomStatus);

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
