info:
  name: query.applications
  type: graphql
  seq: 11

graphql:
  method: POST
  url: "{{baseUrl}}/graphql"
  headers:
    - name: Accept
      value: application/json
  body:
    query: |
      query($status: ApplicationStatus) {
        applications(status: $status) {
          id, jobPostingId, status, dateApplied, lastUpdated, notes
        }
      }
    variables: |-
      {
        "status": null
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
