info:
  name: query.applications
  type: graphql
  seq: 10

graphql:
  method: POST
  url: "{{baseUrl}}/graphql"
  headers:
    - name: Accept
      value: application/json
  body:
    query: |
      query($status: ApplicationStatus, $source: Source) {
        applications(status: $status, source: $source) {
          id, company, role, source, postingUrl, status, dateApplied, lastUpdated, notes, resume { id }
        }
      }
    variables: |-
      {
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
