info:
  name: query.application
  type: graphql
  seq: 12

graphql:
  method: POST
  url: "{{baseUrl}}/graphql"
  headers:
    - name: Accept
      value: application/json
  body:
    query: |
      query($id: ID!) {
        application(id: $id) {
          id, company, role, source, postingUrl, status, dateApplied, lastUpdated, notes, resume { id }
        }
      }
    variables: |
      {
        "id": "{{randomId}}"
      }
  auth: inherit

runtime:
  variables:
    - name: randomId
      value: ece646ae-b317-450f-9de9-2b592fc20bcb

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
