FROM ghcr.io/graalvm/native-image-community:25 AS native-build
WORKDIR /app
COPY . .
RUN ./mvnw install -DskipTests && ./mvnw -Pnative native:compile -pl bootstrap-server -DskipTests

# Use a minimal base image for the runtime
FROM gcr.io/distroless/base:nonroot
COPY --from=native-build /app/bootstrap-server/target/job-tracker-server /app/
EXPOSE 8880
ENTRYPOINT ["/app/job-tracker-server"]
